In [1]:
# Dependencies
import pandas as pd
import numpy as np

In [2]:
# Store filepath in a variable
trump_csv = "output/Trumpholdallthetweets.csv"

# Read our Data file with the pandas library
trump_df = pd.read_csv(trump_csv, encoding = "utf-8", header=None)
trump_df.columns = ("Longitude", "Latitude", "Tweet Text", "City-State", "Long-Lat-Both")

In [3]:
# Show just the header 
trump_df.head()

,Longitude,Latitude,Tweet Text,City-State,Long-Lat-Both
0,-84.580124,39.026611,Just a reminder that @AlanDersh is not a Democ...,"Fort Mitchell, KY","[-84.580124, 39.026611]"
1,-88.473228,30.144425,@richieny70 @StateDept @realDonaldTrump @POTUS...,"Alabama, USA","[-88.473228, 30.144425]"
2,-118.668404,33.704538,Democrats set a trap for #Trump trying to unle...,"Los Angeles, CA","[-118.668404, 33.704538]"
3,-118.448451,33.976882,@MarvinEAdams @politico It's not the vast majo...,"Culver City, CA","[-118.4484512, 33.976882]"
4,-117.296536,33.858759,It�s obvious that Steve Cortez considers himse...,"Moreno Valley, CA","[-117.296536, 33.858759]"

In [4]:
# set up additional columns to hold information
# trump_df['Compound'] = ""
# trump_df['Positive'] = ""
# trump_df['Neutral'] = ""
# trump_df['Negative'] = ""

# trump_df.head()

In [5]:
# Import and Initialize Sentiment Analyzer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

compound_list = []

for index, row in trump_df.iterrows():
    
    target_text = row["Tweet Text"]
    
    # Run analysis
    results = analyzer.polarity_scores(target_text)
    results

    # Run analysis
    compound = results["compound"]
    pos = results["pos"]
    neu = results["neu"]
    neg = results["neg"]
    
    compound_list.append(compound)
    
#print(compound)
#print(pos)

In [6]:
trump_df["Compound_Sentiment"] = compound_list

In [7]:
trump_df

,Longitude,Latitude,Tweet Text,City-State,Long-Lat-Both,Compound_Sentiment
0,-84.580124,39.026611,Just a reminder that @AlanDersh is not a Democ...,"Fort Mitchell, KY","[-84.580124, 39.026611]",0.1695
1,-88.473228,30.144425,@richieny70 @StateDept @realDonaldTrump @POTUS...,"Alabama, USA","[-88.473228, 30.144425]",-0.4003
2,-118.668404,33.704538,Democrats set a trap for #Trump trying to unle...,"Los Angeles, CA","[-118.668404, 33.704538]",-0.5106
3,-118.448451,33.976882,@MarvinEAdams @politico It's not the vast majo...,"Culver City, CA","[-118.4484512, 33.976882]",0.0000
4,-117.296536,33.858759,It�s obvious that Steve Cortez considers himse...,"Moreno Valley, CA","[-117.296536, 33.858759]",0.0000
5,-93.748550,32.419303,@realDonaldTrump We love you President Trump!,"Bossier City, LA","[-93.74855, 32.419303]",0.6696
6,-73.789950,40.982445,@PattyArquette Not at all. \r\n\r\nTrump�s ins...,"White Plains, NY","[-73.78995, 40.982445]",0.3612
7,-158.115354,21.332074,At my age entertainment is everything. Trump i...,"Makakilo, HI","[-158.115354, 21.332074]",0.7964
8,-80.234090,26.210625,@funder Trump should be Charged W/RICO *,"Margate, FL","[-80.2340902, 26.2106246]",-0.2023
9,-118.668404,33.704538,https://t.co/CnqD91jUPA\r\n@realDonaldTrump it...,"Los Angeles, CA","[-118.668404, 33.704538]",0.0000
10,-84.120656,35.663386,A question for men: How does it feel to be the...,"Maryville, TN","[-84.120656, 35.663386]",0.0000
11,-83.095428,42.623997,@AbbyLea68 @kari_andel @ShafPatel @realDonaldT...,"Shelby, MI","[-83.095428, 42.623997]",-0.1531
12,-157.950476,21.254837,@guardian Wrong! The Trump era is defined by a...,"Honolulu, HI","[-157.950476, 21.254837]",-0.5255
13,-97.287293,37.509588,Everyone should be realizing why tRump refused...,"Derby, KS","[-97.287293, 37.509588]",-0.3595
14,-80.203991,26.320692,@SoldByWendy @ChrisMurphyCT No Obama &amp; Tru...,"Boca Raton, FL","[-80.2039913, 26.320692]",-0.3612
15,-118.178345,34.098569,@dapplegraypony @FoxNews @realDonaldTrump @Hil...,"South Pasadena, CA","[-118.1783453, 34.0985693]",0.0000
16,-118.037546,33.973234,It is Trump.,"Hacienda Heights, CA","[-118.037546, 33.973234]",0.0000
17,-118.037546,33.973234,There can b extradition of Trump.,"Hacienda Heights, CA","[-118.037546, 33.973234]",0.0000
18,-89.431339,36.003989,@hemantmehta Evangelical is a POLITICAL DESIGN...,"Dyersburg, TN","[-89.431339, 36.003989]",0.5893
19,-157.950476,21.254837,@guardian Wrong! The Trump era is defined by a...,"Honolulu, HI","[-157.950476, 21.254837]",-0.5255
20,-115.316075,35.960753,"Trump is described as ""refusing to leave his p...","Enterprise, NV","[-115.316075, 35.9607531]",-0.5574
21,-83.200169,39.832013,@DiXiEjO68 @BillAustinJr @galupnorth @Ralphige...,"Columbus, OH","[-83.200169, 39.832013]",-0.4585
22,-106.645646,25.837092,Reporter faces death threats over Trump questi...,"Texas, USA","[-106.645646, 25.837092]",-0.9574
23,-122.436232,47.495315,@DB_Houston_2017 @SpeakNoEvil85 Congratulation...,"Seattle, WA","[-122.436232, 47.4953154]",0.8356
24,-73.821895,40.748782,@CNN If history is any precursor to the lesson...,"Murray Hill, Queens","[-73.821895, 40.748782]",0.5859
25,-83.675290,36.540739,Who turned over a rock and uncovered this Nean...,"Virginia, USA","[-83.67529, 36.540739]",-0.4019
26,-118.144082,33.974263,@thehill Well of course Trump with only beat O...,"Montebello, CA","[-118.144082, 33.974263]",-0.5256
27,-96.977527,32.620678,Devin Nunes goes berserk after as Trump-Russia...,"Dallas, TX","[-96.977527, 32.620678]",-0.4404
28,-94.043628,28.855128,@ChristianIAm07 @SteveSMiller1 @USAMilitaryUSA...,"Louisiana, USA","[-94.043628, 28.855128]",0.0000
29,-122.436232,47.495315,@thomas_bleske @NickPenner26 @vaswati16th @Joe...,"Seattle, WA","[-122.436232, 47.4953154]",0.0000
...,...,...,...,...,...,...
4905,-93.846184,41.528008,@sam_vinograd Seems like Trump is acting kinda...,"West Des Moines, IA","[-93.8461837, 41.5280075]",0.6124
4906,-100.529410,31.335769,@perfectsliders @AK_VaporCharms I think Presid...,"San Angelo, TX","[-100.52941, 31.3357694]",0.0000
4907,-118.668404,33.704538,40 syrian people die brutally and Trump destro...,"Los Angeles, CA","[-118.668404, 33.704538]",-0.9413
4908,-88.026334,42.028374,Mission accomplished Trump? What mission? Atta...,"Arlington Heights, IL","[-88.026334, 42.028374]",-0.7677
4909,-76.711520,39.197211,"Mike Pence, the guy who genuinely believes th...","Baltimore, MD","[-76.7115205, 39.197211]",-0.2960
4910,-124.482003,32.528832,@rebeinstein @SB_da_GHOST_xxx @Captainmarvel89...,"California, USA","[-124.482003, 32.528832]",-0.5574
4911,-87.634643,24.396308,@LawyerRogelio This knocked out was so telling...,"Florida, USA","[-87.634643, 24.396308]",0.1759
4912,-75.303353,40.222978,Did we hear trump or his dog speaking no I thi...,"Lansdale, PA","[-75.303353, 40.222978]",-0.2960
4913,-83.209206,42.533782,@SchuetteOnDuty @POTUS Bill Schuette is wrong ...,"Troy, MI","[-83.209206, 42.5337815]",-0.6114
4914,-91.513080,36.970298,@rmasher2 @realDonaldTrump Ha! Bush’s ex guy A...,"Illinois, USA","[-91.51308, 36.970298]",0.4559
4915,-96.954509,33.202712,Although I question VP Pence’s judgmental atti...,"Paloma Creek South, TX","[-96.954509, 33.202712]",0.0000
4916,-80.519851,39.719801,@LETellerVA @WritersBlq @realDonaldTrump My bu...,"Pennsylvania, USA","[-80.519851, 39.719801]",0.0000
4917,-95.234584,29.590570,@Observer2541 @MissKitteh87 @liberal_resist @E...,"Pasadena, TX","[-95.2345837, 29.59057]",-0.3182
4918,-83.353955,32.046830,@FoxNews why is the Press continually asking i...,"South Carolina, USA","[-83.353955, 32.04683]",0.4404
4919,-82.551469,42.607706,@GOTAllDayLong @FriendEden100 Trump needed to ...,"Algonac, MI","[-82.551469, 42.607706]",-0.5719
4920,-112.323914,33.290260,Donald Trump really with the shits... https://...,"Phoenix, AZ","[-112.3239143, 33.29026]",0.0000
4921,-95.774704,35.995476,@TruthMaga @SultryAssassin1 @girl4_trump @busy...,"Missouri, USA","[-95.774704, 35.995476]",0.0000
4922,-73.977838,40.345652,@Mike_Press19 @USAmericaFans1 Obama is a Marxi...,"Sea Bright, NJ","[-73.977838, 40.345652]",0.8074
4923,-106.645646,25.837092,Barack Obama tried to appease terrorists. Pres...,"Texas, USA","[-106.645646, 25.837092]",-0.7840
4924,-90.500805,38.675851,"Well, another precedent setting step by 45 \r\...","Maryland Heights, MO","[-90.5008048, 38.675851]",0.2732
4925,-84.348855,33.764565,We finna go into war but y’all want trump (the...,"Druid Hills, GA","[-84.3488546, 33.764565]",-0.8442
4926,-118.448451,33.976882,@nachosarah I noticed trump's bright red crotc...,"Culver City, CA","[-118.4484512, 33.976882]",0.4404
4927,-94.258061,30.200365,No... its BS for Anyone to ave this happen... ...,"Lumberton, TX","[-94.258061, 30.200365]",0.0000
4928,-118.668404,33.704538,Yo @IvankaTrump https://t.co/gUTKwrVRZw,"Los Angeles, CA","[-118.668404, 33.704538]",0.0000
4929,-122.210758,47.300531,"Wow, the comment by the commentator was rude. ...","Lea Hill, WA","[-122.2107576, 47.300531]",-0.1531
4930,-102.051769,36.993110,"@LdyDrums @AuspiciousTruth And FYI, there’s no...","Kansas, USA","[-102.051769, 36.9931101]",-0.3542
4931,-73.838271,40.984413,Trump so gangsta,"Greenville, NY","[-73.838271, 40.984413]",0.0000
4932,-73.962582,40.541722,I blame Trump https://t.co/J75M46fUMW,"Queens, NY","[-73.962582, 40.541722]",-0.3400
4933,-95.686106,29.543372,@Sweetie2262 No political outrage vsTrump but ...,"Sugar Land, TX","[-95.686106, 29.5433718]",-0.9451
4934,-71.160356,42.352429,@samswey “We have to be radically inclusive in...,"Cambridge, MA","[-71.160356, 42.352429]",0.4019