In [1]:
#SentimentSearchEngine

# Dependencies
import pandas as pd


from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [2]:
#pass a CSV of tweets into df, run sentiment analysis
#Create a path to the csv and read it into a Pandas DataFrame


csv_path = "output/holdallthetweetsB.csv"

bey_df = pd.read_csv(csv_path, header=None)

bey_df.columns = ["Longitude","Latitude","Tweet Text", "City&State", "Lat&Long Together"]

# set up additional columns to hold information
#bey_df["Compound Sentiment"] = ""

bey_df.head()

,Longitude,Latitude,Tweet Text,City&State,Lat&Long Together
0,-95.234584,29.590570,Be the Beyonc√© in my life or maybe be an angel...,"Pasadena, TX","[-95.2345837, 29.59057]"
1,-80.321683,25.709040,Request #1 - Beyonc√© ‚ÄúIrreplaceable‚Äù @seanetta...,"Miami, FL","[-80.321683, 25.7090404]"
2,-95.823268,29.522325,Cardi B: Beyonc√© on my stereo; \nüó£RESENTMENTüó£ ...,"Houston, TX","[-95.823268, 29.522325]"
3,-76.420402,36.786146,Justin Timberlake ft Beyonc√© x until the end o...,"Portsmouth, VA","[-76.420402, 36.786146]"
4,-73.933612,40.785365,Oh how I wish I was going to #Coachella this y...,"Bronx, NY","[-73.933612, 40.785365]"

In [3]:
#create a list to hold compound sentiments
compound_sentiments = []

# use iterrows to iterate through pandas dataframe
for index, row in bey_df.iterrows():
    
    target_sample = row["Tweet Text"]

    # Run Vader Analysis on each tweet
    results = analyzer.polarity_scores(target_sample)

    # Run analysis
    compound = results["compound"]
    #pos = results["pos"]
    #neu = results["neu"]
    #neg = results["neg"]
    
    # Add each value to the appropriate list
    compound_sentiments.append(compound)

    # Print Analysis
    #print(target_sample)
    #print("Compound Score:", compound)
    #print("Positive Score:", pos)
    #print("Neutral Score:", neu)
    #print("Negative Score: ", neg)
            
    # Print the Averages
    #print(f"User: {target_user}")
    #print(f"Compound: {np.mean(compound_sentiments):.3f}")
    
#print(compound_sentiments)

In [4]:
column_values = pd.Series(compound_sentiments)
bey_df.insert(loc=5, column="Compound Sentiment",value=column_values)

bey_df.head(15)

,Longitude,Latitude,Tweet Text,City&State,Lat&Long Together,Compound Sentiment
0,-95.234584,29.590570,Be the Beyonc√© in my life or maybe be an angel...,"Pasadena, TX","[-95.2345837, 29.59057]",0.0000
1,-80.321683,25.709040,Request #1 - Beyonc√© ‚ÄúIrreplaceable‚Äù @seanetta...,"Miami, FL","[-80.321683, 25.7090404]",0.0000
2,-95.823268,29.522325,Cardi B: Beyonc√© on my stereo; \nüó£RESENTMENTüó£ ...,"Houston, TX","[-95.823268, 29.522325]",0.0000
3,-76.420402,36.786146,Justin Timberlake ft Beyonc√© x until the end o...,"Portsmouth, VA","[-76.420402, 36.786146]",0.0000
4,-73.933612,40.785365,Oh how I wish I was going to #Coachella this y...,"Bronx, NY","[-73.933612, 40.785365]",0.4588
5,-118.668404,33.704538,Men cheat and it feels shitty but then I think...,"Los Angeles, CA","[-118.668404, 33.704538]",0.8658
6,-82.620093,27.821353,I thought Beyonc√© told y‚Äôall I was irreplaceable.,"Tampa, FL","[-82.620093, 27.821353]",0.0000
7,-95.823268,29.522325,I look at young thug like y‚Äôall do with Beyonc...,"Houston, TX","[-95.823268, 29.522325]",0.6597
8,-105.301776,39.953552,Never gets old üòÇ #beyonce #theoffice https://t...,"Boulder, CO","[-105.3017759, 39.953552]",0.0000
9,-73.941941,40.677082,This whole thing with Nicki Minaj and Cardi B ...,"Bushwick, Brooklyn","[-73.941941, 40.677082]",-0.5815
10,-117.053546,32.743581,So......Cardi and Nicki are both killing it no...,"La Mesa, CA","[-117.053546, 32.743581]",-0.6597
11,-109.060257,36.992427,@ciara @StephenCurry30 @Ludacris @lilwayne @1f...,"Colorado, USA","[-109.060257, 36.992427]",0.0000
12,-80.897800,33.441959,Perfect remix with beyonce and one! https://t....,"Orangeburg, SC","[-80.8978, 33.441959]",0.6114
13,-115.384091,36.129459,Beyonce https://t.co/2HY0GhoLRH,"Las Vegas, NV","[-115.384091, 36.129459]",0.0000
14,-97.557572,35.606823,Beyonc√© is really a mood right now,"Edmond, OK","[-97.557572, 35.606823]",0.0000

In [5]:
bey_mean = bey_df["Compound Sentiment"].mean()
print(bey_mean)

TypeError: must be str, not float